config/routes.rb
Rails.application.routes.draw do

  get '/home',                    to: 'home#show'
  post '/auth/github',            as: 'login'
  get '/auth/github/callback',    to: 'sessions#create'
  get '/logout',                  to: 'sessions#destroy'
  get '/auth/failure',            to: 'home#show'

  resources :repos,  only: [:index]
  resources :issues, only: [:index, :create]

  get  '/repos/:repo_name',             to: 'repos#show',   as: :repo
  post '/repos/:repo_name/:has_issues', to: 'repos#create', as: 'create_repo'
  post '/repos/:repo_name',             to: 'repos#activate_repo_issues', as: 'activate_repo_issues'
  delete '/repos/:repo_name',           to: 'repos#destroy'

  get  '/repos/:repo_name/issues/new',  to: 'issues#new',   as: :new_repo_issue
  post '/update_issue_labels/:number',  to: 'issues#update_issue_labels', as: :update_issue_labels
  post '/update_issue_times/:issue_number/:time',  to: 'issues#update_issue_times', as: :update_issue_times

  patch '/update_issues/:number', to: 'issues#update', as: :update_issues

  post  '/update_card_status', to: 'issues#update_card_status'
  get  '/issue_labels/:number', to: 'repos#issue_labels', as: 'issue_labels'

  root 'repos#index'
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  include GithubCardStatusUpdater
  include GithubIssueCreater
  include GithubIssueUpdater

  def new
    @labels     = client.issues.labels.list
    @milestones = client.issues.milestones.list
  end

  def self.create
    @create || GithubIssueCreater
  end

  def self.create=(create)
    @create = create
  end

  def create
    repo_name =  params[:repo_name]
    client.repo = repo_name

    labels = params.has_key?(:creation) ? params[:creation][:labels] : []

    labels << params[:timer_time] << 'Backlog'

    IssuesController.create.call(client:    client,
                                 title:     params[:title],
                                 body:      params[:body],
                                 milestone: params[:milestone],
                                 labels:    labels)

    flash[:success] = "Issue Created!"
    redirect_to repo_path(repo_name)
  end


  def self.update
    @update || GithubIssueUpdater
  end

  def self.update=(update)
    @update = update
  end

  def update
    IssuesController.update.call(
      client: client,
      number: params[:number],
      title:  params[:title],
      body:   params[:body],
      labels: params[:labels])
    head :ok
  end

  def self.update_card_status
    @update_card_status || GithubCardStatusUpdater
  end

  def self.update_card_status=(update_card_status)
    @update_card_status = update_card_status
  end

  def update_card_status

    IssuesController.update_card_status.call(
      client:     client,
      owner:      params[:owner],
      repo:       params[:repo],
      number:     params[:number],
      old_column: params[:oldcolumn],
      new_column: params[:newcolumn])

    head :ok
  end

  private

  def client
    current_user.github
  end
end

app/helpers/issues_helper.rb
module IssuesHelper

  def label_data?(label_name)
    statuses.include?(label_name) || times.include?(label_name) ? true : false
  end

  def set_default_time(time)
    time == '5' ? true : false
  end

  def set_original_time(time, original_time)
    time == original_time ? true : false
  end

  def milestone_or_repo_name(issue)
    return issue.milestone.title if issue.milestone
    "No Milestone set"
  end
end

app/views/issues/new.html.haml
.row
  .col-md-6.col-md-offset-3
    %h1.text-center
      New Issue
    .panel.panel-default
      .panel-body
        .well
          = form_tag issues_path, class: "form", id: 'issue-form', method: :post do
            = text_field_tag :title, nil, placeholder: "Title", class: "issue-text-field form-control"
            = text_area_tag :body, nil, rows: 5, placeholder: "User story...", class: "issue-text-area form-control"
            = hidden_field_tag :repo_name, current_repo
            %br
            .row.form-group
              .col-md-4
                .text-center
                  %strong
                    Select Labels
                - @labels.each do |label|
                  %label{ class: "#{label.name} btn btn-default new-issue-labels", style: "background-color:\##{label.color}" }
                    = check_box_tag "creation[labels][]", [label.name]
                    = label.name
              .col-md-4
                %label.max-width.text-center{:for => "milestone"}
                  Select Milestone
                  %select#milestone.form-control{ name: 'milestone' }
                    - @milestones.each do |milestone|
                      %option{ id: "milestone-#{milestone.number}", value: "#{milestone.number}" }=milestone.title
              .col-md-4
                %label.max-width.text-center{:for => "timer_time"}
                  Select Timer
                  %select#timer_time.form-control{ name: 'timer_time' }
                    - timer_values.each do |k, v|
                      %option{ id: "#{k}", selected: "#{set_default_time(k)}", value: "#{k}" }=v
            .clearfix
              %button.btn.btn-primary.pull-right{:type => "submit"} Create Issue