config/routes.rb
Rails.application.routes.draw do

  get '/home',                    to: 'home#show'
  post '/auth/github',            as: 'login'
  get '/auth/github/callback',    to: 'sessions#create'
  get '/logout',                  to: 'sessions#destroy'
  get '/auth/failure',            to: 'home#show'

  resources :repos,  only: [:index]
  resources :issues, only: [:index, :create]

  get  '/repos/:repo_name',             to: 'repos#show',   as: :repo
  post '/repos/:repo_name/:has_issues', to: 'repos#create', as: 'create_repo'
  post '/repos/:repo_name',             to: 'repos#activate_repo_issues', as: 'activate_repo_issues'
  delete '/repos/:repo_name',           to: 'repos#destroy'

  get  '/repos/:repo_name/issues/new',  to: 'issues#new',   as: :new_repo_issue
  post '/update_issue_labels/:number',  to: 'issues#update_issue_labels', as: :update_issue_labels
  post '/update_issue_times/:issue_number/:time',  to: 'issues#update_issue_times', as: :update_issue_times

  patch '/update_issues/:number', to: 'issues#update', as: :update_issues

  post  '/update_card_status', to: 'issues#update_card_status'
  get  '/issue_labels/:number', to: 'repos#issue_labels', as: 'issue_labels'

  root 'repos#index'
end

app/views/shared/_dropdown_label_form.html.haml
%div{ class: "dropdown pull-left", id: "#{issue.number}" }
  %button{ class: "btn btn-default dropdown-toggle", id: "dropdown-#{issue.number}",
           'aria-expanded': "true",
           'aria-haspopup': "true",
           'data-toggle': "dropdown", type: "button" }
    %strong
      Labels
    %span.caret
  .dropdown-menu{"aria-labelledby" => "dropdown-#{issue.number}" }
    - @labels.each do |label|
      .label-box-dropdown{ class: "#{label.name} labels-#{issue.number} btn btn-xs",
                           style: "background-color:\##{label.color}" }
        %label
          = check_box_tag "updates[labels][]", [label.name], has_label?(issue.labels, label.name)
          = label.name

app/views/shared/_dropdown_repo_list.html.haml
#dropdown-repos-menu.list-group.dropdown-menu{"aria-labelledby" => "dLabel"}
  - repos.each do |repo|
    .row.list-group-item
      - if repo.has_issues
        - if current_user_added_repo(repo.name)
          .col-xs-10.col-md-11
            = link_to repo.name, repo_path(repo.name), class: "#{repo.name}-added btn btn-default repo-btn focus"
          .col-xs-2.col-md-1
            = link_to '-', repo_path(repo.name), method: 'delete', class: "pull-right #{repo.name}-added #{repo.name}-delete-btn btn btn-default focus repo-choice"
        - else
          .col-xs-10.col-md-11
            = link_to repo.name, create_repo_path(repo.name, repo.has_issues.to_s), method: :post, class: "#{repo.name} btn btn-default repo-btn"
          .col-xs-2.col-md-1
            = link_to '+', create_repo_path(repo.name, repo.has_issues.to_s), method: 'post', class: "pull-right #{repo.name}-add-btn btn btn-default repo-choice"
      - else
        .col-xs-10.col-md-11
          = link_to repo.name, activate_repo_issues_path(repo.name), method: :post, class: "#{repo.name}add-btn btn btn-default repo-btn disabled"
        .col-xs-2.col-md-1
          = link_to '+', activate_repo_issues_path(repo.name), method: 'post', class: "pull-right #{repo.name}-add-btn btn btn-default repo-choice", :rel => "tooltip", :title => "Activate Issues"

app/views/shared/_dropdown_timer_form.html.haml
.form-group.pull-right
  %label{:for => "timer-time"}
    %select#timer-time.form-control{ class: "timer-time-#{issue.number}", name: 'timer-time' }
      - timer_values.each do |k, v|
        %option{ class: "", name: 'timer-time', value: "#{k}" }=v

app/views/shared/_issue_form.html.haml
= text_area_tag :title, issue.title, { rows: 1, class: "form-control noscrollbars ctrl-enter title-#{issue.number}", :onkeyup => "autoGrow(this);"}
= text_area_tag :body, issue.body, { rows: 5, class: "form-control noscrollbars ctrl-enter body-#{issue.number}", :onkeyup => "autoGrow(this);"}
= hidden_field_tag :labels, issue.labels.map { |label| label.name}

:javascript
  function autoGrow (oField) {
    if (oField.scrollHeight > oField.clientHeight) {
      oField.style.height = oField.scrollHeight + "px";
    }
  };

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-fixed-top.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-toggle" => "collapse", "data-target" => "#ontarget-navbar"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "OnTarget", root_path, class: 'navbar-brand'
    #ontarget-navbar.collapse.navbar-collapse
      - if current_user
        %form.navbar-form.navbar-left{:role => "search"}
          .form-group
            %input#search_repos.form-control{ :placeholder => "Search for a Repo", :type => "text" }
        = render partial: 'shared/dropdown_repo_list', locals: { repos: @repos }
        %ul.nav.navbar-nav
          - if current_repo
            %li
              = link_to 'New Issue', new_repo_issue_path(current_repo) unless current_repo.empty?
        %span.sr-only
          Toggle Navigation
        %ul.nav.navbar-nav.navbar-right
          %li
            =link_to "Logout", logout_path, id: 'logout'
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            =link_to 'Login with Github', login_path, method: :post

app/views/shared/_repo_list.html.haml
.list-group.dropdown-menu{"aria-labelledby" => "dLabel"}
  - repos.each do |repo|
    - if current_user_added_repo(repo.name) && repo.has_issues
      .list-group-item
        = link_to repo.name, repo_path(repo.name), class: "#{repo.name}-added btn btn-default repo-btn focus"
        = link_to '-', repo_path(repo.name), method: 'delete', class: "#{repo.name}-added #{repo.name}-delete-btn btn btn-default focus repo-choice"
    - else
      - if repo.has_issues
        .list-group-item
          = link_to repo.name, create_repo_path(repo.name, repo.has_issues.to_s), method: :post, class: "#{repo.name} btn btn-default repo-btn"
          = link_to '+', create_repo_path(repo.name, repo.has_issues.to_s), method: 'post', class: "#{repo.name}-add-btn btn btn-default btn-large repo-choice"
      - else
        .list-group-item
          = link_to repo.name, activate_repo_issues_path(repo.name), method: :post, class: "#{repo.name}add-btn btn btn-default repo-btn disabled"
          = link_to '+', activate_repo_issues_path(repo.name), method: 'post', class: "#{repo.name}-add-btn btn btn-default btn-large repo-choice", :rel => "tooltip", :title => "Activate Issues"